### ISSUE TITLE
Getting Http 403 when using GetListsMetadata

### ISSUE THREAD

**Issue by Manav-Seth** [stoiveyp/Alexa.NET.ListManagement#9]
I am using the code sample straight out of readme. Log snippet:

2018-10-18T06:36:20.3881258+00:00 0HLHKODQ3I8LB:00000001 [ERR] Connection id ""0HLHKODQ3I8LB"", Request id ""0HLHKODQ3I8LB:00000001"": An unhandled exception was thrown by the application. (560e7d32)
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)
   at Alexa.NET.ListManagementClient.GetListsMetadata()

**Comment by stoiveyp** [comment]
Hi @Manav-Seth 

403 means a problem with permissions so let's check off the initial causes (travelling at the moment so can't run a sample just at the moment)

- The skill you've got the API Token from has list read permissions enabled (this is found in the permissions tab of the skill page in the Alexa dashboard)
- The user you're testing as has granted list read permission to your skill (if you go to the skill settings in your Alexa app/website there's a green tick next to the permissions)

Let me know either way, if both of those are set correctly then I'll try and run some samples when I'm able.

**Comment by Manav-Seth** [comment]
Thanks for the quick response. I was trying this out on my under developed skill (and I never really intend to publish it anyways - it’s for personal use). And turns out, even for development apps, I have to turn ON permissions in the Alexa app. Did that and it all works. Thanks so much.
